feature/debut-src commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 #
 # This file is part of Algol 68 Genie - an Algol 68 interpreter.
-# Copyright (C) 2001-2007 J. Marcel van der Veer <algol68g@xs4all.nl>.
+# Copyright (C) 2001-2008 J. Marcel van der Veer <algol68g@xs4all.nl>.
 #
 # This program is free software; you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free Software
@@ -19,13 +19,14 @@
 # configure: configuring script for Algol 68 Genie.
 #
 
-prompt="++++"
 A68G_NAME="a68g"
 MAKEFILE=makefile
-VERSION_NUMBER="11"
+VERSION_NUMBER="11.1"
 REVISION="Mark $VERSION_NUMBER"
-YEAR="2007"
-TIME_STAMP="November $YEAR"
+RR_NUMBER="1.0"
+MONTH="March"
+YEAR="2008"
+TIME_STAMP="$MONTH $YEAR"
 RELEASE_DATE="released $TIME_STAMP"
 PACKAGE="algol68g-mk$VERSION_NUMBER"
 warnings=
@@ -46,7 +47,7 @@ TEST_FILE="$USR_CHK/regression"
 BATCH_FILE="$USR_CHK/regression.bat"
 LINK_COLOUR="blue"
 BACKGROUND_COLOUR="#e0e0e0"
-echo "$prompt $A68G_NAME $REVISION $RELEASE_DATE ($PACKAGE) `uname -mrs`"
+echo "$A68G_NAME $REVISION $RELEASE_DATE ($PACKAGE) `uname -mrs`"
 #
 USERID=`whoami`
 POWERPC=`uname -a | grep powerpc`
@@ -66,6 +67,7 @@ opt=
 prev_arg=
 threads=no
 warn="-w"
+dist_opt=no
 for arg in "$@"
 do
 # Handle option = value
@@ -97,6 +99,8 @@ do
 	-debug | --debug)
 		opt=`echo $opt "-ggdb"`
 		ld_opt=`echo $ld_opt "-ggdb"` ;;
+	-dist | --dist)
+		dist_opt=;;
 	-docs | --docs)
 		doc_opt=;;
 	-indent | --indent)
@@ -129,7 +133,7 @@ do
 	-O3)
 		opt=`echo $opt "-O3"` ;;
 	-O4)
-		opt=`echo $opt "-O3 -march=prescott -funroll-loops"` ;;
+		opt=`echo $opt "-O3 -funroll-loops -march=prescott"` ;;
 	-Os)
 		opt=`echo $opt -Os` ;;
 	-threads | --threads)
@@ -174,6 +178,17 @@ then
 	exit 1
 fi
 #
+# Generate distribution
+#
+if [	-z $dist_opt	]
+then
+	cd ..
+	tar -czf $PACKAGE.tar.gz $PACKAGE
+	echo "generated distribution"
+	echo "$0 done"
+	exit
+fi
+#
 # Generate documentation
 #
 if [	-z $doc_opt	]
@@ -182,10 +197,10 @@ then
 	for f in `echo *.html`
 	do
 		echo $f
-		sed "/<!-- Header -->/r header" < $f | sed "/<!-- Footer -->/r footer" | sed "/<!-- Navigation bar -->/r navigation" | sed "s/REVISION/$REVISION/g" | sed "s/TIME_STAMP/$TIME_STAMP/g" | sed "s/PACKAGE/$PACKAGE/g" | sed "s/LINK_COLOUR/$LINK_COLOUR/g" | sed "s/BACKGROUND_COLOUR/$BACKGROUND_COLOUR/g" > ../$f
+		sed "/<!-- Header -->/r header" < $f | sed "/<!-- Footer -->/r footer" | sed "/<!-- Navigation bar -->/r navigation" | sed "/<!-- RRHeader -->/r rr.header" | sed "/<!-- RRFooter -->/r rr.footer" | sed "/<!-- RRNavigation bar -->/r rr.navigation"| sed "s/REVISION/$REVISION/g" | sed "s/TIME_STAMP/$TIME_STAMP/g" | sed "s/PACKAGE/$PACKAGE/g" | sed "s/LINK_COLOUR/$LINK_COLOUR/g" | sed "s/BACKGROUND_COLOUR/$BACKGROUND_COLOUR/g" | sed "s/RR_NUMBER/$RR_NUMBER/g" | sed "s/TAB/\&nbsp;\&nbsp;\&nbsp;\&nbsp;\&nbsp;\&nbsp;/g" > ../$f
 	done
-	echo "$prompt generated documentation"
-	echo "$prompt $0 done"
+	echo "generated documentation"
+	echo "$0 done"
 	exit
 fi
 #
@@ -201,8 +216,8 @@ then
 		rm $f~
 	done
 	wc *.c *.h
-	echo "$prompt indented source"
-	echo "$prompt $0 done"
+	echo "indented source"
+	echo "$0 done"
 	exit
 fi
 #
@@ -227,8 +242,8 @@ then
 	echo "#define A68_PG_VERSION \"\"" 1>>$VERSION_FILE
 	echo "" 1>>$VERSION_FILE
 	echo "#endif" 1>>$VERSION_FILE
-	echo "$prompt generated anonymus version header"
-	echo "$prompt $0 done"
+	echo "generated anonymus version header"
+	echo "$0 done"
 	exit
 fi
 #
@@ -236,7 +251,7 @@ fi
 #
 if ! [  -w "`pwd`"	]
 then
-	echo "$prompt exiting: $USERID cannot write to `pwd`"
+	echo "exiting: $USERID cannot write to `pwd`"
 	exit 1
 fi
 #
@@ -244,11 +259,11 @@ fi
 #
 if [    -z $cc  ]
 then
-	echo -n "$prompt checking C compiler in $SYS_BIN: "
+	printf "checking C compiler in $SYS_BIN ... "
 	if [    -f $SYS_BIN/gcc ]
 	then
 		cc=gcc
-		if [ -n OPENBSD ]
+		if [ -n "$OPENBSD" ]
 		then
 			opt=`echo $opt "-pthread"`
 		fi
@@ -268,7 +283,7 @@ fi
 # Find default USR_INC if none was given
 if [    -z $USR_INC     ]
 then
-	echo -n "$prompt include directory: "
+	printf "include directory ... "
 	if [    -d $USR_LOC/include   ]
 	then
 		USR_INC=$USR_LOC/include
@@ -280,7 +295,7 @@ fi
 # Find default USR_LIB if none was given
 if [    -z $USR_LIB     ]
 then
-	echo -n "$prompt library directory: "
+	printf "library directory ... "
 	if [    -d $USR_LOC/lib       ]
 	then
 		USR_LIB=$USR_LOC/lib
@@ -292,7 +307,7 @@ fi
 # Find default USR_BIN if none was given
 if [    -z $USR_BIN     ]
 then
-	echo -n "$prompt target binary directory: "
+	printf "target binary directory ... "
 	if [    -d $USR_LOC/bin       ]
 	then
 		USR_BIN=$USR_LOC/bin
@@ -311,15 +326,15 @@ then
 	echo $USR_BIN
 elif ! [	-d $USR_BIN     ]
 then
-	echo "$prompt exiting: $USR_BIN is not a valid directory"
+	echo "exiting: $USR_BIN is not a valid directory"
 	exit 1
 fi
 if ! [  -w $USR_BIN     ]
 then
-	echo "$prompt $USERID cannot write to $USR_BIN, set to `pwd`"
+	echo "$USERID cannot write to $USR_BIN, set to `pwd`"
 	if [	-f $USR_BIN/a68g ]
 	then
-		echo "$prompt warning: $USR_BIN/a68g already exists which may cause confusion"
+		echo "warning: $USR_BIN/a68g already exists which may cause confusion"
 		warnings=yes
 	fi
 	USR_BIN=`pwd`
@@ -327,7 +342,7 @@ fi
 # Find default man_dir if none was given
 if [    -z $man_dir     ]
 then
-	echo -n "$prompt target man directory: "
+	printf "target man directory ... "
 	if [    -d $USR_LOC/man/man1       ]
 	then
 		man_dir="$USR_LOC/man/man1"
@@ -346,12 +361,12 @@ then
 	echo $man_dir
 elif ! [	-d $man_dir     ]
 then
-	echo "$prompt exiting: $man_dir is not a valid directory"
+	echo "exiting: $man_dir is not a valid directory"
 	exit 1
 fi
 if ! [  -w $man_dir     ]
 then
-	echo "$prompt $USERID cannot write to $man_dir, set to `pwd`"
+	echo "$USERID cannot write to $man_dir, set to `pwd`"
 	man_dir=`pwd`
 fi
 #
@@ -360,16 +375,19 @@ fi
 err=no
 for inc in assert.h ctype.h errno.h fcntl.h limits.h math.h setjmp.h signal.h stdio.h stdlib.h string.h sys/resource.h sys/stat.h sys/time.h sys/times.h sys/types.h sys/wait.h time.h unistd.h
 do
+	printf "checking for $inc ... "
 	if ! [  -f $SYS_INC/$inc	]
 	then
-		echo -n "$prompt $inc: "
-		echo "not found"
+		printf "$inc ... "
+		echo "no"
 		err=yes
+	else
+		echo "yes"
 	fi
 done
 if [    $err = yes      ]
 then
-	echo "$prompt exiting: not all include files found"
+	echo "exiting: not all include files found"
 	exit 1
 fi
 #
@@ -407,7 +425,7 @@ dist:   distclean
 TAGS info dvi:
 	@echo "target not implemented"
 _MAKE_EOF
-echo "$prompt generated $MAKEFILE"
+echo "generated $MAKEFILE"
 #
 # Generate source level makefile
 #
@@ -417,148 +435,146 @@ echo "USR_BIN=$USR_BIN" 1>>$BUILD_FILE
 echo "USR_LIB=$USR_LIB" 1>>$BUILD_FILE
 echo "USR_INC=$USR_INC" 1>>$BUILD_FILE
 echo "CC=$cc" 1>>$BUILD_FILE
-echo "PROMPT=\"$prompt\"" 1>>$BUILD_FILE
 #
 # Shared libraries are called .so (Linux etcetera) or .dylib (BSD).
 #
 # Find POSIX threads
-#if [    -z $threads -a -f $SYS_INC/pthread.h ]
 if [    -z $threads ]
 then
-	echo -n "$prompt checking POSIX threads in $SYS_LIB and $SYS_INC: "
+	printf "checking POSIX threads in $SYS_LIB and $SYS_INC ... "
 	if [ -f $SYS_INC/pthread.h ]
 	then
 		if [ -f $SYS_LIB/libpthread.so -o -f $SYS_LIB/libpthread.a -o -f $SYS_LIB/libpthread.dylib ]
 		then
-			echo "found"
+			echo "yes"
 			echo "POSIX_THREADS_LIBS=-lpthread" 1>>$BUILD_FILE
 			echo "POSIX_THREADS_FLAG=-DENABLE_PAR_CLAUSE" 1>>$BUILD_FILE
 		else
-			echo "not found"
+			echo "no"
 		fi
 	else
-		echo "not found"
+		echo "no"
 	fi
 else
-	echo "$prompt not using POSIX threads; parallel clause will be disabled (specify --threads)"
+	echo "not using POSIX threads; parallel clause will be disabled (specify --threads)"
 fi
 # Find GNU Plotutils
-echo -n "$prompt checking GNU plotutils in $USR_LIB and $USR_INC: "
+printf "checking GNU plotutils in $USR_LIB and $USR_INC ... "
 if [    -f $USR_INC/plot.h ]
 then
 	if [    -f $USR_LIB/libplot.so -o -f $USR_LIB/libplot.a	-o -f $USR_LIB/libplot.dylib	]
 	then
-		echo "found"
+		echo "yes"
 		echo "PLOTUTILS_LIBS=-L/usr/X11R6/lib -lXaw -lXmu -lXt -lSM -lICE -lXext -lX11 -lplot" 1>>$BUILD_FILE
 		echo "PLOTUTILS_FLAG=-DENABLE_GRAPHICS" 1>>$BUILD_FILE
 	else
-		echo "not found"
+		echo "no"
 	fi
 else
-	echo "not found"
+	echo "no"
 fi
 # Find GSL
-echo -n "$prompt checking GNU scientific library in $USR_LIB: "
+printf "checking GNU scientific library in $USR_LIB ... "
 if [    -f $USR_LIB/libgsl.so -o -f $USR_LIB/libgsl.a -o -f $USR_LIB/libgsl.dylib 	]
 then
 	if [    -f $USR_LIB/libgslcblas.so -o -f $USR_LIB/libgslcblas.a -o -f $USR_LIB/libgslcblas.dylib	]
 	then
-		echo "found"
+		echo "yes"
 		echo "GSL_LIBS=-lgsl -lgslcblas" 1>>$BUILD_FILE
 		echo "GSL_FLAG=-DENABLE_NUMERICAL" 1>>$BUILD_FILE
 	else
-		echo "not found"
+		echo "no"
 	fi
 else
-	echo "not found"
+	echo "no"
 fi
 # Find curses
-echo -n "$prompt checking curses in $SYS_LIB: "
+printf "checking curses in $SYS_LIB ... "
 if [    -f $SYS_LIB/libcurses.so -o -f $SYS_LIB/libcurses.a -o -f $SYS_LIB/libcurses.dylib ]
 then
-	echo "found"
+	echo "yes"
 	echo "CURSES_LIBS=-lcurses" 1>>$BUILD_FILE
 	echo "CURSES_FLAG=-DENABLE_CURSES" 1>>$BUILD_FILE
 else
-	echo "not found"
+	echo "no"
 fi
 # Find terminfo 
-echo -n "$prompt checking terminfo in $SYS_INC and $SYS_LIB: "
+printf "checking terminfo in $SYS_INC and $SYS_LIB ... "
 if [    -f $SYS_INC/term.h	]
 then
 	if [    -f $SYS_LIB/libcurses.so -o -f $SYS_LIB/libcurses.a -o -f $SYS_LIB/libcurses.dylib ]
 	then
-		echo "found"
+		echo "yes"
 		echo "TERMINFO_FLAG=-DENABLE_TERMINFO" 1>>$BUILD_FILE
 	else
-		echo "not found"
+		echo "no"
 	fi
 else
-	echo "not found"
+	echo "no"
 fi
 # Find HTTP support
-echo -n "$prompt checking HTTP support in $SYS_INC: "
+printf "checking HTTP support in $SYS_INC ... "
 if [    -f $SYS_INC/netdb.h -a -f $SYS_INC/arpa/inet.h -a -f $SYS_INC/netinet/in.h -a -f $SYS_INC/sys/socket.h	]
 then
-	echo "found"
+	echo "yes"
 	echo "HTTP_FLAG=-DENABLE_HTTP" 1>>$BUILD_FILE
 else
-	echo "not found"
+	echo "no"
 fi
 # Find regular expression support
-echo -n "$prompt checking regular expression support in $SYS_INC: "
+printf "checking regular expression support in $SYS_INC ... "
 if [    -f $SYS_INC/regex.h	]
 then
-	echo "found"
+	echo "yes"
 	echo "REGEX_FLAG=-DENABLE_REGEX" 1>>$BUILD_FILE
 else
-	echo "not found"
+	echo "no"
 fi
 # Find PostgreSQL libraries
-echo -n "$prompt checking PostgreSQL libraries in $SYS_LIB, $USR_LIB and $SQL_DIR: "
+printf "checking PostgreSQL libraries in $SYS_LIB, $USR_LIB and $SQL_DIR ... "
 if [ -f $SQL_DIR/lib/libpq.so -o -f $SQL_DIR/lib/libpq.a -o -f $SQL_DIR/lib/libpq.dylib	]
 then
-	echo "found"
+	echo "yes"
 	echo "SQL_DIR=$SQL_DIR">>$BUILD_FILE
 	echo "SQL_LIBS=-lpq" 1>>$BUILD_FILE
 	echo "SQL_FLAG=-DENABLE_POSTGRESQL" 1>>$BUILD_FILE
 elif [ -f $SYS_DIR/lib/libpq.so -o -f $SYS_DIR/lib/libpq.a -o -f $SYS_DIR/lib/libpq.dylib	]
 then
-	echo "found"
+	echo "yes"
 	echo "SQL_DIR=$SYS_DIR">>$BUILD_FILE
 	echo "SQL_LIBS=-lpq" 1>>$BUILD_FILE
 	echo "SQL_FLAG=-DENABLE_POSTGRESQL" 1>>$BUILD_FILE
 elif [ -f $USR_DIR/lib/libpq.so -o -f $USR_DIR/lib/libpq.a -o -f $USR_DIR/lib/libpq.dylib	]
 then
-	echo "found"
+	echo "yes"
 	echo "SQL_DIR=$USR_DIR">>$BUILD_FILE
 	echo "SQL_LIBS=-lpq" 1>>$BUILD_FILE
 	echo "SQL_FLAG=-DENABLE_POSTGRESQL" 1>>$BUILD_FILE
 else
-	echo "not found"
+	echo "no"
 fi
 # Find IEEE-754 compatibility
-echo -n "$prompt checking IEEE 754 floating point compatibility using system information: "
-if [	-n POWERPC -o -n PPC -o -n X86	]
+printf "checking IEEE 754 floating point compatibility using system information ... "
+if [	-n "$POWERPC" -o -n "$PPC" -o -n "$X86"	]
 then
-	echo "compatible"
+	echo "yes"
 	echo "IEEE_754_FLAG=-DENABLE_IEEE_754" 1>>$BUILD_FILE
 else
 	echo "unknown"
-	echo -n "$prompt checking IEEE 754 floating point support in $SYS_INC: "
+	printf "checking IEEE 754 floating point support in $SYS_INC ... "
 	if [    -f $SYS_INC/ieee754.h -o -f $SYS_INC/ieeefp.h -o -f $SYS_INC/machine/ieeefp.h   ]
 	then
-		echo "found"
+		echo "yes"
 		echo "IEEE_754_FLAG=-DENABLE_IEEE_754" 1>>$BUILD_FILE
 	else
-		echo "not found: if your platform is IEEE 754 compatible then build with 'make CFLAGS=ENABLE_IEEE_754'"
+		echo "no: if your platform is IEEE 754 compatible then build with 'make CFLAGS=ENABLE_IEEE_754'"
 	fi
 fi
 # Finish Makefile
-echo -n "STD_CFLAGS=" 1>>$BUILD_FILE
+printf "STD_CFLAGS=" 1>>$BUILD_FILE
 if [	-d /opt/local/include	]
 then
-	echo -n "-I/opt/local/include " 1>>$BUILD_FILE
+	printf "-I/opt/local/include " 1>>$BUILD_FILE
 fi
 if [    $cc = gcc       ]
 then
@@ -571,10 +587,10 @@ then
 else
 	echo "-I\$(USR_INC)" 1>>$BUILD_FILE
 fi
-echo -n "STD_LD_FLAGS=" 1>>$BUILD_FILE
+printf "STD_LD_FLAGS=" 1>>$BUILD_FILE
 if [	-d /opt/local/lib	]
 then
-	echo -n "-L/opt/local/lib " 1>>$BUILD_FILE
+	printf "-L/opt/local/lib " 1>>$BUILD_FILE
 fi
 if [    $cc = gcc       ]
 then
@@ -599,14 +615,14 @@ a68g:   $(CS)
 	@$(CC) $(CS) $(CFLAGS) $(STD_LD_FLAGS) $(POSIX_THREADS_LIBS) $(PLOTUTILS_LIBS) $(GSL_LIBS) $(CURSES_LIBS) $(SQL_LIBS) -lm $(LD_FLAGS) -o a68g
 $(CS): $(HS)
 .c.o:
-	@echo "$(PROMPT) compiling $<"
+	@echo "compiling $<"
 	@$(CC) -c $(FLAGS) $<
 clean:
 	@rm -f $(CS)
 depend:
 	@touch $(HS)
 _BUILD_EOF
-echo "$prompt generated $BUILD_FILE"
+echo "generated $BUILD_FILE"
 #
 # Make regression script
 #
@@ -680,8 +696,8 @@ done
 _BATCH_EOF
 chmod +x $TEST_FILE
 chmod +x $BATCH_FILE
-echo "$prompt generated $TEST_FILE"
-echo "$prompt generated $BATCH_FILE"
+echo "generated $TEST_FILE"
+echo "generated $BATCH_FILE"
 fi
 #
 # Generate a version header
@@ -723,31 +739,31 @@ fi
 #
 if [    $build = yes    ]
 then
-	echo "$prompt building $PACKAGE"
+	echo "building $PACKAGE"
 	make a68g
 	case $?
 	in
 		0)
 			;;
 		*)
-			echo "$prompt exiting: $?"
+			echo "exiting: $?"
 			exit 1 ;;
 	esac
-	echo -n "$prompt checking whether $PACKAGE works: "
+	printf "checking whether $PACKAGE exists ... "
 	./a68g -version >& /dev/null
 	case $?
 	in
 		0)
 			echo "ok" ;;
 		*)
-			echo "$prompt exiting: $?"
+			echo "exiting: $?"
 			exit 1 ;;
 	esac
 fi
 if [	-z $warnings ]
 then
-	echo "$prompt $0 done"
+	echo "$0 done"
 else
-	echo "$prompt $0 done, with warnings"
+	echo "$0 done, with warnings"
 fi
 exit
